use_frameworks!

platform :ios, '11.0'

target 'ZLGithubOAuth_Example' do
  pod 'ZLGithubOAuth', :path => '../'
  pod 'ZLGithubAPISwift', :git => 'https://github.com/ExistOrLive/ZLGithubAPISwift'
  pod 'Toast-Swift'

  target 'ZLGithubOAuth_Tests' do
    inherit! :search_paths

  end
end
